spring.application.name=Property Management System
#spring.datasource.url=jdbc:postgresql://${DB_HOST}/${DB_NAME}?sslmode=require&channelBinding=require
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=PropertyManagementDB;encrypt=true;trustServerCertificate=true
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASS}
spring.datasource.username=sa
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update



